//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetworkActivityIndicator {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Res {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Res() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NetworkActivityIndicator.Res", typeof(Res).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Average emission speed.
        /// </summary>
        internal static string str_AvgEmissionSpeed {
            get {
                return ResourceManager.GetString("str_AvgEmissionSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Average reception speed.
        /// </summary>
        internal static string str_AvgReceptionSpeed {
            get {
                return ResourceManager.GetString("str_AvgReceptionSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на bit.
        /// </summary>
        internal static string str_bit {
            get {
                return ResourceManager.GetString("str_bit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Bytes.
        /// </summary>
        internal static string str_Bytes {
            get {
                return ResourceManager.GetString("str_Bytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на An error occurred in Network Activity Indicator. We are sorry for this inconvenience and are looking to correct the problem as soon as possible.
        ///Below is displayed the cause of the error that you can send to the developer using a screenshot :.
        /// </summary>
        internal static string str_ErrorCrash {
            get {
                return ResourceManager.GetString("str_ErrorCrash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Gbit.
        /// </summary>
        internal static string str_Gbit {
            get {
                return ResourceManager.GetString("str_Gbit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на GiB.
        /// </summary>
        internal static string str_GiB {
            get {
                return ResourceManager.GetString("str_GiB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Help.
        /// </summary>
        internal static string str_Help {
            get {
                return ResourceManager.GetString("str_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Include in statistics.
        /// </summary>
        internal static string str_IncludeInStatistics {
            get {
                return ResourceManager.GetString("str_IncludeInStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Kbit.
        /// </summary>
        internal static string str_Kbit {
            get {
                return ResourceManager.GetString("str_Kbit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на KiB.
        /// </summary>
        internal static string str_KiB {
            get {
                return ResourceManager.GetString("str_KiB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Mbit.
        /// </summary>
        internal static string str_Mbit {
            get {
                return ResourceManager.GetString("str_Mbit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на MiB.
        /// </summary>
        internal static string str_MiB {
            get {
                return ResourceManager.GetString("str_MiB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No.
        /// </summary>
        internal static string str_No {
            get {
                return ResourceManager.GetString("str_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No IP available.
        /// </summary>
        internal static string str_NoIpAvailable {
            get {
                return ResourceManager.GetString("str_NoIpAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на None.
        /// </summary>
        internal static string str_None {
            get {
                return ResourceManager.GetString("str_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на This feature is not available in this version of Windows!.
        /// </summary>
        internal static string str_NotAvailableWinver {
            get {
                return ResourceManager.GetString("str_NotAvailableWinver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Not connected.
        /// </summary>
        internal static string str_NotConnected {
            get {
                return ResourceManager.GetString("str_NotConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Instantaneous emission speed.
        /// </summary>
        internal static string str_RawEmissionSpeed {
            get {
                return ResourceManager.GetString("str_RawEmissionSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Instantaneous reception speed.
        /// </summary>
        internal static string str_RawReceptionSpeed {
            get {
                return ResourceManager.GetString("str_RawReceptionSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Received.
        /// </summary>
        internal static string str_Received {
            get {
                return ResourceManager.GetString("str_Received", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sent.
        /// </summary>
        internal static string str_Sent {
            get {
                return ResourceManager.GetString("str_Sent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Statistics.
        /// </summary>
        internal static string str_Statistics {
            get {
                return ResourceManager.GetString("str_Statistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Tbit.
        /// </summary>
        internal static string str_Tbit {
            get {
                return ResourceManager.GetString("str_Tbit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на TiB.
        /// </summary>
        internal static string str_TiB {
            get {
                return ResourceManager.GetString("str_TiB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unsupported.
        /// </summary>
        internal static string str_Unsupported {
            get {
                return ResourceManager.GetString("str_Unsupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на A value below 50ms could possibly use too much CPU !.
        /// </summary>
        internal static string str_WarningContent {
            get {
                return ResourceManager.GetString("str_WarningContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No network interface is currently selected for statistics : it means that the icon in the notification area and the notification window will no longer be updated !.
        /// </summary>
        internal static string str_WarningNoInterfaceSelected {
            get {
                return ResourceManager.GetString("str_WarningNoInterfaceSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Warning.
        /// </summary>
        internal static string str_WarningNoInterfaceSelectedCaption {
            get {
                return ResourceManager.GetString("str_WarningNoInterfaceSelectedCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Warning !.
        /// </summary>
        internal static string str_WarningTitle {
            get {
                return ResourceManager.GetString("str_WarningTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Yes.
        /// </summary>
        internal static string str_Yes {
            get {
                return ResourceManager.GetString("str_Yes", resourceCulture);
            }
        }
    }
}
